services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - vicalvez_network
    volumes:
      - wp_data:/var/www/wordpres
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: always
  wordpress:
    container_name: wordpress
    env_file: .env
    ports:
      - "9000:9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on: 
      - mariadb
    restart: always
    networks:
      - vicalvez_network
    volumes:
      - wp_data:/var/www/wordpress
  mariadb:
    container_name: mariadb
    networks:
      - vicalvez_network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

volumes:
  wp_data:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/vicalvez/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/vicalvez/data/mariadb'
networks:
  vicalvez_network:
    driver: bridge
