services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - vicalvez_network
    volumes:
      - wp_data:/var/www/wordpres
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: always
  wordpress:
    container_name: wordpress
    env_file: .env
    ports:
      - "9000:9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on: 
      - mariadb
    restart: always
    networks:
      - vicalvez_network
    volumes:
      - wp_data:/var/www/wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
  mariadb:
    container_name: mariadb
    networks:
      - vicalvez_network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env      
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

volumes:
  wp_data:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/vicalvez/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/vicalvez/data/mariadb'
networks:
  vicalvez_network:
    driver: bridge
